name = "Galnfriends"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4afcc58274719119a98f08acf445dac58dbbd1323277f5c10cf380f43a6724c"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
