name = "Galnfriends"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7d6d68b0acd14b647e6f6a3a9e41eac02e169fd16f5102899dcd4ba02462e81"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
