name = "Galnfriends"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaf64051abfd0c773db7afc03d874b67cb3849858c9178621fd365fcb71ba554"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
